### ISSUE TITLE
Feat: Enhance the test runs page

### ISSUE THREAD

**Issue by gowtham-ra** [guidewire-oss/fern-ui#14]
**Improvements:**
1. [x] Sort the page in reverse chronological order so that the latest test runs should be listed in the beginning.
2. [x] Maintain the state of the tags' colour so that each tag with the same name should have the same colour everywhere.
3. [x] Test failure messages should be pre-formatted text and should be presented exactly as it is received from the API. Example: If the text has a newline character `\n`, the proceeding text should start from a new line.
4. [x] Add a column to display the date and time of each test run

**Comment by tedd-E** [comment]
Closed as part of #17. 
![image](https://github.com/user-attachments/assets/a7092d0d-5f41-47d1-8796-f135aaea775a)
