### ISSUE TITLE
Feat: Create a summary page with green/red boxes to show at the aggregate level with ability to drill down

### ISSUE THREAD

**Issue by anoop2811** [guidewire-oss/fern-ui#4]
Take this as an inspiration: https://github.com/vakenbolt/go-test-report?tab=readme-ov-file#understanding-html-test-report

We should start with a summary page that should show me the following:
1. List of Project names that I have access to
2. Each summary run of the project showing green or red ie. if we have a test that fails in any of the test suites part of a test run for that project, the box should be red, else it should be green
3. I should be able to click on a single box which represents a single test run which should take me to the detail page of that run showing all the test runs as we have it currently in the home page
4. When we hover over the green/red boxes, it should show how many tests passed out of total tests say for example if its a red box, it can show something like 30/32 (93.75%) etc

**Comment by tedd-E** [comment]
Closed as a part of #15.
![image](https://github.com/user-attachments/assets/7145593b-be68-4139-8b6f-808fd81ff247)
